spring.application.name=veebipood

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.file.name=logs.log

everypay.username=e36eb40f5ec87fa2
everypay.password=7b91a3b9e1b74524c2e9fc282f8ac8cd
everypay.base-url=https://igw-demo.every-pay.com/api/v4
everypay.customer-url=https://err.ee
jwt.secret-key=JojzZYmVkg4tObLwAkaD2dYOCL4BDsAVbwEnJTeSkoI


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=e9f784b04799b6
spring.mail.password=39bbfb5b787fb1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

frontend.url=http://localhost:5173
